# Generated by Django 3.0.3 on 2023-01-29 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pfam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(max_length=25)),
                ('domain_description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=30)),
                ('sequence', models.CharField(max_length=256)),
                ('length', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_id', models.CharField(max_length=15)),
                ('clade', models.CharField(default='E', max_length=1)),
                ('genus', models.CharField(max_length=256)),
                ('species', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Protein_Domain_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('pfam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteins.Pfam')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteins.Protein')),
            ],
        ),
        migrations.AddField(
            model_name='protein',
            name='domains',
            field=models.ManyToManyField(through='proteins.Protein_Domain_link', to='proteins.Pfam'),
        ),
        migrations.AddField(
            model_name='protein',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteins.Taxonomy'),
        ),
    ]
